### ISSUE TITLE
[VoiceOver] Verbs in 'Browse' are not read out in Spanish.

### ISSUE THREAD

**Issue by SpacyRicochet** [vermont42/Conjugar#7]
The verbs in the 'Browse' menu at the beginning are read out in English, which makes them very weird to hear.

**Comment by vermont42** [comment]
One workaround is to run the app with the device in Spanish mode. As shown [here](https://vimeo.com/470320768/60643b8831), VoiceOver then pronounces the verbs correctly. A side benefit is that the user can then enjoy the awesome Spanish localization.

Looks like you may have found a better solution. I would welcome a PR, but I note that any `UILabel` that shows Spanish exclusively should get the fix. I don't believe the fix is appropriate for the Help `UITextView` because that may contain a lot of non-Spanish (currently, English) text.

As an aside, the whole app could use an accessibility audit. That is in my backlog.
